---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: awx-backup-role
  namespace: awx
rules:
- apiGroups: ["awx.ansible.com"]
  resources: ["awxbackups"]
  verbs: ["get", "list", "create", "delete"]
...
