---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awx-backup-rolebinding
  namespace: awx
subjects:
- kind: ServiceAccount
  name: default  # Service account used by your CronJob, adjust if using a different one
  namespace: awx
roleRef:
  kind: Role
  name: awx-backup-role  # Reference the role you just created
  apiGroup: rbac.authorization.k8s.io

